---
- name: Buscar admin.conf do Kubernetes, ajustar IP e salvar como ~/.kube/config localmente
  hosts: master
  become: true
  vars:
    kubeconfig_local: "{{ lookup('env','HOME') }}/.kube/config"
  tasks:
    - name: Garantir que a pasta .kube existe no host de controle
      delegate_to: localhost
      file:
        path: "{{ lookup('env','HOME') }}/.kube"
        state: directory
        mode: '0700'

    - name: Buscar /etc/kubernetes/admin.conf do nó master
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/admin.conf
        flat: yes

    - name: Obter IP do nó master
      ansible.builtin.set_fact:
        master_ip: "{{ ansible_host }}"

    - name: Substituir 127.0.0.1 pelo IP do master no kubeconfig
      delegate_to: localhost
      ansible.builtin.replace:
        path: /tmp/admin.conf
        regexp: '127\.0\.0\.1'
        replace: "{{ master_ip }}"

    - name: Mover kubeconfig ajustado para ~/.kube/config
      delegate_to: localhost
      ansible.builtin.copy:
        src: /tmp/admin.conf
        dest: "{{ kubeconfig_local }}"
        mode: '0600'