apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: allow-node-exporter-host-access
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  exceptions:
  - policyName: "disallow-host-namespaces"
    ruleNames:
    - "host-namespaces"
    - "autogen-host-namespaces"
  - policyName: "disallow-host-path" 
    ruleNames:
    - "host-path"
    - "autogen-host-path"
  - policyName: "disallow-host-ports"
    ruleNames:
    - "host-ports"
    - "autogen-host-ports"
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - Pod
        namespaces:
        - observability
        names:
        - "prometheus-prometheus-node-exporter*"
        - "loki-promtail*"