apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 5.9.4
    helm:
      values: |
        controller:
          installPlugins:
            - kubernetes:latest  
            - workflow-aggregator:latest
            - git:latest
            - configuration-as-code:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
