apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 5.9.4
    helm:
      values: |
        controller:
          serviceType: NodePort
          servicePort: 8080
          nodePort: 32000
          probes:
            startupProbe:
              failureThreshold: 60
              periodSeconds: 10
              timeoutSeconds: 5
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          javaOpts: "-Xms512m -Xmx512m"
          installPlugins:
            - kubernetes:latest  
            - workflow-aggregator:latest
            - git:latest
            - configuration-as-code:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
