apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.3
    chart: loki-stack
    helm:
      values: |
        loki:
          config:
            limits_config:
              volume_enabled: true
          persistence:
            enabled: true
            storageClassName: "nfs-client"
            size: 10Gi
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "3100"
            
        promtail:
          enabled: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "3101"
          config:
            snippets:
              extraScrapeConfigs: |
                - job_name: edgerouter_syslog
                  syslog:
                    listen_address: 0.0.0.0:514
                    listen_protocol: udp
                    idle_timeout: 60s
                    label_structured_data: yes
                    labels:
                      job: "syslog"
                      host: "edgerouter"
                  relabel_configs:
                    - source_labels: ['__syslog_message_hostname']
                      target_label: 'hostname'
          extraPorts:
            syslog:
              containerPort: 514
              protocol: UDP
              hostPort: 514
  destination:
    server: https://kubernetes.default.svc
    namespace: observability 
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
