apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 28.14.1
    chart: prometheus
    helm:
      values: |
        alertmanager:
          enabled: false
        pushgateway:
          enabled: false
        prometheus-node-exporter:
          enabled: true

        server:
          extraScrapeConfigs: |
            - job_name: 'snmp_edgerouter'
              static_configs:
                - targets:
                  - 192.168.27.1
              metrics_path: /snmp
              params:
                module: [if_mib]
                auth: [homelab_v2]
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: snmp-exporter-prometheus-snmp-exporter.observability.svc.cluster.local:9116 # Points to the internal exporter service
          persistentVolume:
            enabled: true
            storageClass: "nfs-client"
            size: 10Gi
          
          service:
            type: NodePort
            nodePort: 32090

          retention: "15d"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: observability 
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true