apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snmp-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.13.1
    chart: prometheus-snmp-exporter
    helm:
      values: |
        config:
          default:
            version: 2
            auth:
              community: homelab-snmp
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true