apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.4.3
    helm:
      values: |
        crds:
          install: false
        server:
          service:
            type: NodePort
            nodePort: 30080
        configs:
          params:
            server.insecure: true
        controller:
          replicas: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    # Ignore the NodePort if an external provider or TF is shifting it
    - group: ""
      kind: Service
      name: argocd-server
      jsonPointers:
        - /spec/ports/0/nodePort
    # Ignore the password and keys that Terraform changes every run
    - group: ""
      kind: Secret
      name: argocd-secret
      jsonPointers:
        - /data/admin.password
        - /data/admin.passwordMtime
        - /data/server.secretkey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
